services:
  go-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./src:/app
    ports:
      - 8080:8080
    tty: true # コンテナの永続化
    #env_file: # .envファイル
    #  - ./.go_env
    environment:
      - TZ=Asia/Tokyo